host: https://192.168.8.254
version: 1.4
auth:
  user: admin
  password: Pwd123456
projects:
  - release
  - library
policy:
  includePublic: true
  numberPolicy:
    number: 1
  retainTags:
    - 1.30.2