# Host of the Harbor
host: https://dev.cargo.io
# Version of the Harbor, e.g. 1.7, 1.4.0
version: 1.7
# Admin account
auth:
  user: admin
  password: Pwd123456
# Projects list to clean images for, it you want to clean images for all
# projects, leave it empty.
projects: []
# Policy to clean images
policy:
  # Policy type, e.g. "number", "recentlyNotTouched", "regex"
  type: regex

  # Number policy: to retain the latest N tags for each repo
  #numberPolicy:
  #  number: 5

  # Regex policy: only clean images that match the given repo patterns and tag patterns
  regexPolicy:
    # Regex to match repos, a repo will be regarded as matched when it matches any regex in the list
    repos: [".*"]
    # Regex to match tags, a tag will be regarded as matched when it matches any regex in the list
    tags: [".*-alpha.*", "dev"]

  # Tags that should be retained anyway, '?', '*' supported.
  retainTags: []
